dependencies:
  build:
    - ruby:2.6.0

build_targets:
  - name: default
    commands:
      - gem install bundler -v 1.8
      - bundle install
      - rspec

ci:
  builds:
    - name: tests
      build_target: default

#test commit

